<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>ExamBuilder.App</RootNamespace>
    <AssemblyName>ExamBuilder</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExamBuilder.Domain\ExamBuilder.Domain.csproj" />
    <ProjectReference Include="..\ExamBuilder.Data\ExamBuilder.Data.csproj" />
  </ItemGroup>

</Project>
